// <auto-generated />
namespace MoneyBox.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class build5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(build5));
        
        string IMigrationMetadata.Id
        {
            get { return "201701040633122_build5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
